FROM ruby:3.1

RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  curl

# Install Node.js 20 and Yarn 1.22
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
  apt-get install -y nodejs && \
  npm install -g yarn

WORKDIR /myapp

COPY Gemfile /myapp/Gemfile
COPY Gemfile.lock* /myapp/
COPY package.json /myapp/package.json
COPY yarn.lock* /myapp/

RUN bundle install
RUN yarn install

COPY . /myapp

EXPOSE 3000
